Repository uavorg/uavstack, pull requests merged in 2018-07, with the labels that each got.

#338 The memory leak problem of apphubManager
  com.creditease.uav.healthmanager.buildComponent/bin/run.sh
  com.creditease.uav.healthmanager.buildComponent/config/agent.properties
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/AppHubManager.java
Labels: bug

#340 Optimization of log collection system && fix the issue of log lost problem
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/LogAgent.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/ReliableTaildirEventReader.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TaildirLogComponent.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/far/DefaultLogFilterAndRule.java
  com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/ReliableTaildirEventReader.java
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/healthmanager/newlog/handlers/NewLogDataMessageHandler.java
Labels: bug, enhancement

#348 Reduce redis lpop operation from JudgeNotifyTaskForTimer
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTaskForTimer.java
Labels: enhancement

#346 Each application instance performance under application cluster performance in application monitoring can be linked to its own performance page&&Windows traffic collection for non-admin account, unable to get the list of network card devices out of bounds array
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procdetectagent/NetworkIoDetector.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.appmonitor.js
Labels: bug, enhancement

#343 Support tomact-jdbc connection pool
  com.creditease.uav.hook.jdbc/pom.xml
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/JdbcHookProxy.java
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/interceptors/JdbcDriverIT.java
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/pools/tomcatjdbc/TomcatJdbcHookProxy.java
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/pools/tomcatjdbc/interceptors/TomcatJdbcIT.java
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
Labels: enhancement

#354 fix invokeChain NPE in some certain scenarios
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/handlers/ClientSpanInvokeChainHandler.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/span/SpanFactory.java
Labels: bug

#355 Springboot support PropertiesLauncher starts as Main-Class
  com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/SpringBootTomcatAdaptor.java
  com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/agent/trans/MOFClsTransformer.java
Labels: enhancement

#351 The tmax and tmin reset cycles are shortened to the default 1 hour&&The initial time the mof gets tmax is empty, and NullPointerException is thrown
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/captureframework/spi/CaptureConstants.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/handlers/AbsServerRespTimeCapHandler.java
Labels: bug, enhancement
