Repository uavorg/uavstack, pull requests merged in 2018-04, with the labels that each got.

#241 Modify HM distribution deployment url
  README.md
Labels: enhancement

#248 fix mdf Parse failure while inserting into mongoDB
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/healthmanager/messaging/AbstractMessageHandler.java
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/DataStoreHelper.java
Labels: bug

#243 Optimal es configuration
  com.creditease.uav.elasticsearch.client/src/main/java/com/creditease/uav/elasticsearch/client/ESClient.java
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/healthmanager/newlog/HMNewLogIndexMgr.java
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/InvokeChainIndexMgr.java
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/SlowOperIndexMgr.java
  com.creditease.uav.threadanalysis/src/main/java/com/creditease/uav/threadanalysis/server/ThreadAnalysisIndexMgr.java
Labels: enhancement

#246 OpenTSDB optimization and real time data view
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.appmonitor.js
  com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/core/OpentsdbDataStore.java
Labels: bug, enhancement

#250 HM's server side invokeChain data Span for IllegalArgumentException.
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/collect/InvokeChainDataCollectHandler.java
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/data/Span.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/span/Span.java
Labels: bug

#252 base/link-relative notify support time_limit&&support metric's time aggregate value notify
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/css/uav.notifystgy.css
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.win.js
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/NotifyStrategy.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/StrategyJudgement.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTimerTask.java
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/DateTimeHelper.java
  com.creditease.uav.hook.mq/src/main/java/com/creditease/uav/hook/rabbitmq/interceptors/RabbitmqIT.java
Labels: enhancement

#254 define uavagent default JAppGroup UAV
  com.creditease.uav.agent.buildComponent/bin/run.sh
Labels: enhancement

#260 logagent optimization
  com.creditease.uav.agent.buildComponent/config/agent.properties
  com.creditease.uav.agent.buildComponent/config/ma_pro.properties
  com.creditease.uav.agent.buildComponent/config/ma_test.properties
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/LogAgent.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/ReliableTaildirEventReader.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TailFileTaskJob.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TaildirLogComponent.java
  com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/ReliableTaildirEventReader.java
Labels: enhancement

#256 Add esclient hook && FIX logback profile is incomplete
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.appstream.js
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.win.js
  com.creditease.uav.hook.esclient/.gitignore
  com.creditease.uav.hook.esclient/findbugs.exclude.xml
  com.creditease.uav.hook.esclient/pom.xml
  com.creditease.uav.hook.esclient/src/main/java/com/creditease/uav/hook/esclient/transport/TransportHookProxy.java
  com.creditease.uav.hook.esclient/src/main/java/com/creditease/uav/hook/esclient/transport/interceptors/TransportIT.java
  com.creditease.uav.hook.esclient/src/main/java/com/creditease/uav/hook/esclient/transport/invokeChain/TransportAdapter.java
  com.creditease.uav.hook.esclient/src/test/java/com/creditease/uav/hook/esclient/DoTestTransportHookProxy.java
  com.creditease.uav.loghook/src/main/java/com/creditease/uav/log/hook/LogBackHookProxy.java
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
  com.creditease.uav.monitorframework.buildComponent/pom.xml
  com.creditease.uav.monitorframework.buildFat/pom.xml
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/invokechain/ElasticsearchService.java
Labels: bug, enhancement

#261 add kafka hook
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.apm.js
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/StringHelper.java
  com.creditease.uav.hook.mq/pom.xml
  com.creditease.uav.hook.mq/src/main/java/com/creditease/uav/hook/kafka/KafkaHookProxy.java
  com.creditease.uav.hook.mq/src/main/java/com/creditease/uav/hook/kafka/interceptors/KafkaIT.java
  com.creditease.uav.hook.mq/src/main/java/com/creditease/uav/hook/kafka/invokeChain/KafkaConsumerAdapter.java
  com.creditease.uav.hook.mq/src/main/java/com/creditease/uav/hook/kafka/invokeChain/KafkaProducerAdapter.java
  com.creditease.uav.hook.mq/src/test/java/com/creditease/uav/hook/mq/DoTestkafkaHookProxy.java
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
  com.creditease.uav.monitorframework.buildComponent/pom.xml
  com.creditease.uav.monitorframework.buildFat/pom.xml
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/queue/KafkaTest.java
Labels: enhancement

#262 logagent optimization
  com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/ReliableTaildirEventReader.java
Labels: enhancement

#263 modify kafka config
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
Labels: enhancement
