Repository uavorg/uavstack, pull requests merged in 2018-06, with the labels that each got.

#295 add initialization value of rocketmq consumer
  com.creditease.uav.healthmanager.buildComponent/config/agent.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_pro_apmserver.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_test_apmserver.properties
  com.creditease.uav.messaging/src/main/java/com/creditease/uav/messaging/api/MessagingFactory.java
  com.creditease.uav.messaging/src/main/java/com/creditease/uav/messaging/impl/RMQMessageConsumer.java
  com.creditease.uav.messaging/src/test/java/test/messaging/TestRMQMessageConsumer.java
  com.creditease.uav.notifymanager/src/main/java/com/creditease/agent/feature/common/MessageProducerResourceComponent.java
  com.creditease.uav.notifymanager/src/main/java/com/creditease/agent/feature/common/messaging/StandardMessagingBuilder.java
  org.uavstack.resources.common/src/main/java/org/uavstack/resources/common/messaging/StandardMessagingBuilder.java
Labels: enhancement

#302 MonitorFramework fails to build if MonitorAgent does not built first
  com.creditease.uav.monitorframework.buildComponent/pom.xml
Labels: bug

#303 UAV JDK9 ENHANCEMENT
  com.creditease.uav.agent.buildComponent/bin/run.sh
  com.creditease.uav.agent.buildComponent/bin/start.bat
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/JVMToolHelper.java
  com.creditease.uav.helper/src/main/java/com/creditease/uav/helpers/url/BASE64DecoderUrl.java
  com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/agent/MOFAgent.java
  com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/agent/trans/MOFClsTransformer.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/supporters/ThreadAnalysisSupporter.java
  com.creditease.uav.monitorframework.buildComponent/extlib/9/javassist.jar
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/handlers/JVMStateCapHandler.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java
Labels: enhancement

#312 Enhance account access to LDAP information&&Fix the mailbox information query with an array out of bounds
  com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/sso/GUISSOLdapClient.java
Labels: bug, enhancement

#305 AppID support configuration
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/util/MonitorServerUtil.java
Labels: enhancement

#307 webService client support
  com.creditease.uav.hook.jaxws/src/main/java/com/creditease/uav/hook/jaxws/JaxWSCxfHookProxy.java
  com.creditease.uav.hook.jaxws/src/main/java/com/creditease/uav/hook/jaxws/interceptors/JaxWSCxfHookIT.java
  com.creditease.uav.hook.jaxws/src/main/java/com/creditease/uav/hook/jaxws/interceptors/JaxWSHookIT.java
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/invokechain/WSService.java
Labels: enhancement

#309 fix logagent can not collect log
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/BaseHttpMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/jmx/JMXAppServerMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/jmx/JMXJavaMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/handlers/LogProfileDataNotifyHandler.java
Labels: bug

#316 The invokechain failed to record the HTTP500 request correctly&& Incorrect SQL operation type judgment
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/interceptors/JdbcDriverIT.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/slowoper/adapter/ServerSpanAdapter.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/jee/filters/GlobalFilter.java
Labels: bug

#319 client profile data whit "," cause strategy instances undesirable expectations & ivc.data cause NPE
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.add.js
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/listeners/InvokeChainClsInjectListener.java
Labels: bug

#329 Change the blacklist and whitelist strategy of client url profiling
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/captureframework/MonitorUrlFilterMgr.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/handlers/ClientRespTimeCapHandler.java
Labels: enhancement

#325 The Redis thread pool adds a refusal policy
  com.creditease.uav.cache.redis/src/main/java/com/creditease/uav/cache/redis/AredisAsyncService.java
Labels: bug

#327 logger profile support log4j2 && support log4j AsyncAppender
  com.creditease.uav.loghook/pom.xml
  com.creditease.uav.loghook/src/main/java/com/creditease/uav/log/hook/Log4j2HookProxy.java
  com.creditease.uav.loghook/src/main/java/com/creditease/uav/log/hook/Log4jHookProxy.java
  com.creditease.uav.loghook/src/main/java/com/creditease/uav/log/hook/interceptors/LogIT.java
  com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/SpringBootTomcatAdaptor.java
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
  com.creditease.uav.monitorframework.buildFat/pom.xml
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/Log4j2Test.java
  com.creditease.uav.monitorframework.buildFat/src/main/webapp/WEB-INF/web.xml
  com.creditease.uav.monitorframework.buildFat/src/resource/java/log4j2.xml
Labels: enhancement

#326 Gets the start time of the process
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procdetectagent/OSProcessScanner.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/uavnetwork/js/uav.network.js
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/DateTimeHelper.java
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/OSProcessHelper.java
Labels: enhancement

#330 Get process display time (modify display BUG)
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/uavnetwork/js/uav.network.js
Labels: bug

#332 The log is too large to cause the insert data to fail
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/healthmanager/newlog/HMNewLogIndexMgr.java
Labels: bug

#334 fix the problem of profiling webservice url error about some applications
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java
Labels: bug
