Repository uavorg/uavstack, pull requests merged in 2018-05, with the labels that each got.

#276 jedis hook support spring-dada-redis && FIX Alarm convergence 4 hours judged as new alarm Event does not take effect
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/NCConstant.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/actions/CEMailAction.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/handlers/NCJudgementHandler.java
Labels: bug, enhancement

#270 Apphub授权新增关键字 & datastore api 对 mongodb 原生主键“_id”的支持 & fix ldap 查询卡主 & fix hm使用多个opentsdb配置被覆盖 & fix datastore opentsdb http超时配置无效
  com.creditease.uav.console.buildComponent/config/web_pro.xml
  com.creditease.uav.console.buildComponent/config/web_test.xml
  com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/filter/SessionAsyncFilter.java
  com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/rest/GUIService.java
  com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/sso/GUISSOClient.java
  com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/sso/GUISSOLdapClient.java
  com.creditease.uav.console/src/main/java/com/creditease/uav/manage/rest/ManageRestService.java
  com.creditease.uav.console/src/main/java/com/creditease/uav/manage/rest/entity/GroupEntity.java
  com.creditease.uav.console/src/main/webapp/WEB-INF/web.xml
  com.creditease.uav.console/src/main/webapp/apphub/js/main.temp.js
  com.creditease.uav.console/src/main/webapp/uavapp_manage/groupmanage/js/group.add.js
  com.creditease.uav.console/src/main/webapp/uavapp_manage/groupmanage/js/group.del.js
  com.creditease.uav.console/src/main/webapp/uavapp_manage/groupmanage/js/group.modfy.js
  com.creditease.uav.console/src/main/webapp/uavapp_manage/groupmanage/js/group.searchbar.js
  com.creditease.uav.console/src/main/webapp/uavapp_manage/groupmanage/js/group.table.js
  com.creditease.uav.console/src/main/webapp/uavapp_manage/groupmanage/js/restful.client.js
  com.creditease.uav.console/src/main/webapp/uavapp_manage/groupmanage/main.html
  com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/core/MongoDBDataStore.java
  com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/core/OpentsdbDataStore.java
  com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/mongo/MongodbImplStrategy.java
  com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/source/OpentsdbDataSource.java
Labels: bug, enhancement

#272 Fix http parameter messy code in heavy invoke chain data
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/RewriteIvcRequestWrapper.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/jee/JEEServiceRunGlobalFilterHandler.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/slowoper/adapter/ServerSpanAdapter.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/slowoper/handlers/HttpServerSlowOperHandler.java
Labels: bug

#280 Authorization to add keyword matching to Apphub
  com.creditease.uav.console/src/main/java/com/creditease/uav/manage/rest/ManageRestService.java
Labels: bug

#281 modify README.md
  README.md
  README中文版.md
  Readme-EN
Labels: enhancement

#285 time_based notification support notify cross diffirent metric type
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/RuntimeNotifyCatcher.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/NotifyStrategy.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/StrategyJudgement.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/AbstractExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/AppExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/ClientExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/HostExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/JvmExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/ProcExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/ServerExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/expradaptors/UrlExprAdaptor.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/TimerNotifyWorker.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTaskForTimer.java
Labels: enhancement

#284 The problem with the semicolon in iplink has led to the application of the portrait.
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/IPLinkProfileHandler.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/util/MonitorServerUtil.java
Labels: bug

#291 invokechain data query enhancement
  com.creditease.uav.console/src/main/java/com/creditease/uav/godeye/rest/APMRestService.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/css/uav.appmonitor.css
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.apm.js
  com.creditease.uav.invokechain/src/main/java/com/creditease/uav/invokechain/http/InvokeChainQueryHandler.java
Labels: enhancement

#292 change the key of jvmInfos map from workerId to workerName in detector
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/BaseDetector.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/JVMContainerOSDetector.java
Labels: enhancement

#288 Httpclients record return code && Alarm recording related alarm strategy
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifymgr/js/notify.desc.temp.js
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.win.js
  com.creditease.uav.healthmanager.buildComponent/config/JTAmail.template
  com.creditease.uav.healthmanager.buildComponent/config/mail.template
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/NotifyStrategy.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/StrategyJudgement.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/NodeInfoWatcher.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/RuntimeNotifyStrategyMgr.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTask.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTaskForTimer.java
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/StringHelper.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/handlers/ClientRespTimeCapHandler.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ClientProfileHandler.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/spi/ProfileConstants.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/actions/AbstractMailAction.java
Labels: enhancement
