Repository uavorg/uavstack, pull requests merged in 2018-03, with the labels that each got.

#200 fix target jvm output dump when MA attach other user's jvm
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/JVMToolHelper.java
Labels: bug

#199 method invoke chain support for springboot
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/listeners/InvokeChainClsInjectListener.java
Labels: enhancement

#203 还原
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procdetectagent/NetworkIoDetector.java
Labels: help wanted

#209 Fix NO DB pool data problem
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/pools/c3p0/C3P0HookProxy.java
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/pools/dbcp/DBCPHookProxy.java
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/pools/hikari/HikariHookProxy.java
  com.creditease.uav.hook.jdbc/src/main/java/com/creditease/uav/hook/jdbc/pools/mybatis/MybatisHookProxy.java
  com.creditease.uav.monitorframework.buildFat/pom.xml
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/TestRestService.java
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/mybatis/User.java
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/mybatis/UserMapper.xml
  com.creditease.uav.monitorframework.buildFat/src/main/java/com/creditease/monitorframework/fat/mybatis/mybatis-config.xml
Labels: bug

#207 Fix NPE in profile data parsing
  com.creditease.uav.base/src/main/java/com/creditease/agent/profile/api/StandardProfileModeler.java
Labels: bug

#205 Under the Windows system, MA runs for a long time, and the traffic collection opens the network card device too much.
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procdetectagent/NetworkIoDetector.java
Labels: bug

#215 struts2 profile enhancement
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java
Labels: enhancement

#213 fix issues when enable both http&&jmx detect
  com.creditease.uav.agent.buildComponent/config/ma_pro.properties
  com.creditease.uav.agent.buildComponent/config/ma_test.properties
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/BaseDetector.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/DetectorManager.java
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/datastore/DataObserver.java
Labels: enhancement

#217 Increase gradient alarm convergence
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/procwatch/ProcWatcher.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/css/uav.notifystgy.css
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.add.js
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/notifystgy/js/notifystgy.win.js
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/NotifyStrategy.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/NodeInfoWatcher.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyCommonTask.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTask.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/task/JudgeNotifyTimerTask.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/NotificationCenter.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/NCConstant.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/NCEventStatusManager.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/handlers/NCJudgementHandler.java
  com.creditease.uav.notifycenter/src/main/java/com/creditease/agent/feature/notifycenter/task/PersistentTask.java
Labels: enhancement

#224 Fix the problem of some alarm records cannot be queried
  com.creditease.uav.console.buildComponent/config/web_pro.xml
  com.creditease.uav.console.buildComponent/config/web_test.xml
  com.creditease.uav.console/src/main/java/com/creditease/uav/godeye/rest/GodEyeRestService.java
  com.creditease.uav.console/src/main/webapp/WEB-INF/web.xml
Labels: bug

#222 get log file information according to invokeChain
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.apm.js
Labels: bug

#226 HttpDataCatchWorker do not close httpclient
  com.creditease.uav.agent.buildComponent/config/agent.properties
  com.creditease.uav.agent.buildComponent/config/ma_pro.properties
  com.creditease.uav.agent.buildComponent/config/ma_test.properties
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/hbagent/HeartBeatServerLifeKeeper.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/BaseHttpMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/BaseMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/jmx/JMXAppServerMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/jmx/JMXJavaMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/BaseDetector.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/JVMContainerOSDetector.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.appmonitor.js
  com.creditease.uav.healthmanager.buildComponent/config/agent.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_pro_apphubmgr.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_pro_hbserver.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_pro_pfntfyserver.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_test_pnhbserver.properties
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/healthmanager/HealthManagerProfileDataLifeKeeper.java
Labels: bug

#223 Multi-search items supporting for Apphub SearchBar
  com.creditease.uav.console/src/main/webapp/apphub/js/common/mvc.js
Labels: enhancement

#227 Fixed NodeInfo data is too large
  com.creditease.uav.healthmanager.buildComponent/config/hm_pro_apmserver.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_pro_rtserver.properties
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/RuntimeNotifySliceMgr.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/StrategyJudgement.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/NodeInfoWatcher.java
Labels: bug

#230 fix MA HTTP Detector detect same process repeatedly&&conflicts between jmx and http detector
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/MonitorAgent.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/BaseMonitorDataCatchWorker.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/BaseDetector.java
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/detect/JVMContainerOSDetector.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.appstream.js
Labels: bug, enhancement

#233 Change admin's password
  com.creditease.uav.console.buildComponent/config/web_pro.xml
  com.creditease.uav.console.buildComponent/config/web_test.xml
Labels: enhancement

#237 Apphub Ulog Client Ip Incorrect bug fix
  com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/filter/SessionAsyncFilter.java
  com.creditease.uav.console/src/main/java/com/creditease/uav/apphub/rest/GUIService.java
  com.creditease.uav.console/src/main/java/com/creditease/uav/godeye/rest/GodEyeRestService.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/jee/JEEServiceRunGlobalFilterHandler.java
Labels: bug

#239 optimize DataLoggerManager and PLogger
  com.creditease.uav.healthmanager.buildComponent/config/agent.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_pro_pfntfyserver.properties
  com.creditease.uav.healthmanager.buildComponent/config/hm_test_pnhbserver.properties
  com.creditease.uav.logging/src/main/java/com/creditease/agent/log/PLogger.java
  com.creditease.uav.logging/src/main/java/com/creditease/agent/log/api/IPLogger.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/UAVServer.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/globalfilter/jee/UAVServerJEEController.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/log/DataLogger.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/log/DataLoggerManager.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java
Labels: enhancement
