Repository uavorg/uavstack, pull requests merged in 2018-12, with the labels that each got.

#461 Copy function bugFix in the helper.js
  com.creditease.uav.console/src/main/webapp/apphub/js/common/helper.js
Labels: bug

#465 fix issue 464
  com.creditease.uav.agent.buildComponent/bin/run4docker.sh
  com.creditease.uav.agent.buildComponent/bin/run4k8s.sh
  com.creditease.uav.agent.buildComponent/bin/start_ma_pro_docker.sh
  com.creditease.uav.agent.buildComponent/bin/start_ma_pro_k8s.sh
  com.creditease.uav.agent.buildComponent/bin/start_ma_test_docker.sh
  com.creditease.uav.agent.buildComponent/bin/start_ma_test_k8s.sh
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/healthmanager/datastore/adaptors/NodeInfoDataAdapter.java
Labels: enhancement

#463 Redis supports cluster configuration
  com.creditease.uav.cache.redis/pom.xml
  com.creditease.uav.cache.redis/src/main/java/com/creditease/uav/cache/api/CacheManager.java
  com.creditease.uav.cache.redis/src/main/java/com/creditease/uav/cache/redis/LettuceAsyncService.java
  com.creditease.uav.cache.redis/src/main/java/com/creditease/uav/cache/redis/api/CacheFactory.java
Labels: enhancement

#473 Displaying content for log query data bugfix
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/appmonitor/js/uav.log.js
Labels: bug

#471 Process death distinguishes MA dead && Alarm policy can no longer be deleted in memory && The lower limit of the same-loop warning calculation may be incorrect
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/StrategyJudgement.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/NodeInfoWatcher.java
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/runtimenotify/scheduler/RuntimeNotifyStrategyMgr.java
Labels: bug, enhancement

#467 SystemStarter log print NetCardName
  com.creditease.uav.base/src/main/java/com/creditease/agent/SystemStarter.java
Labels: enhancement
