Repository uavorg/uavstack, pull requests merged in 2018-08, with the labels that each got.

#365 Fix the problem of failed portraits when the anno of the WebService is empty & The following versions of springboot1.3 (including) support SpringApplication starting as main-class
  com.creditease.uav.base/src/main/java/com/creditease/agent/profile/api/StandardProfileModeler.java
  com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/SpringBootTomcatAdaptor.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ComponentProfileHandler.java
Labels: bug, enhancement

#363 Alarm record query optimization
  com.creditease.uav.console/src/main/java/com/creditease/uav/godeye/rest/GodEyeRestService.java
  com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/core/MongoDBDataStore.java
  com.creditease.uav.dbaccess/src/main/java/com/creditease/uav/datastore/mongo/MongodbImplStrategy.java
  com.creditease.uav.healthmanager/src/test/java/testData/MongoDBQuery/DSfind.json
Labels: enhancement

#361 invokechain enhancement for rabbitmq and low version tomcat
  com.creditease.uav.hook.mq/src/main/java/com/creditease/uav/hook/rabbitmq/interceptors/RabbitmqIT.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/jee/JEEServiceRunGlobalFilterHandler.java
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/slowoper/adapter/ServerSpanAdapter.java
Labels: enhancement

#357 fix URI has "null" substring bug and remove excrescent path in appid
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/profiling/handlers/ClientProfileHandler.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/util/MonitorServerUtil.java
  com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/SpringBootTomcatPlusIT.java
Labels: bug

#368 FIX HttpRequest does'nt contain ip:port causing httpclient profile without http://ip:port
  com.creditease.uav.hook.httpclients/src/main/java/com/creditease/uav/hook/httpclients/async/interceptors/ApacheAsyncHttpClientIT.java
  com.creditease.uav.hook.httpclients/src/main/java/com/creditease/uav/hook/httpclients/sync/interceptors/ApacheHttpClientIT.java
  com.creditease.uav.hook.httpclients/src/main/java/com/creditease/uav/hook/httpclients3/sync/interceptors/ApacheHttpClient3IT.java
Labels: bug

#370 Apphub Authorized user experience enhancement
  com.creditease.uav.console/src/main/webapp/uavapp_godfilter/groupfilter/js/groupfilter.js
  com.creditease.uav.healthmanager/src/main/java/com/creditease/uav/feature/healthmanager/http/handlers/HMCacheQueryHandler.java
Labels: enhancement

#371 Apphub Authorized user experience enhancement
  com.creditease.uav.console/src/main/webapp/uavapp_godfilter/groupfilter/js/groupfilter.js
Labels: enhancement

#373 Add a regular task worker component based on ScheduledThreadPoolExecutor, and delete no use fun in the interface and its implements
  com.creditease.uav.base/src/main/java/com/creditease/agent/spi/ITimerWorkManager.java
  com.creditease.uav.base/src/main/java/com/creditease/agent/workqueue/SystemScheduledWorkMgr.java
  com.creditease.uav.base/src/main/java/com/creditease/agent/workqueue/SystemTimerWorkMgr.java
Labels: enhancement

#375 AredisAsyncService Log Printing Efficiency Optimization
  com.creditease.uav.cache.redis/src/main/java/com/creditease/uav/cache/redis/AredisAsyncService.java
Labels: enhancement

#377 Support all url ignoring && Pathparameter judgment method optimization in http client url && Get LocalIP optimization
  com.creditease.uav.helper/src/main/java/com/creditease/uav/helpers/network/HostNewworkInfo.java
  com.creditease.uav.monitorframework.buildComponent/config/uav.properties
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/captureframework/MonitorUrlFilterMgr.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/handlers/ClientRespTimeCapHandler.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/handlers/ServerEndRespTimeCapHandler.java
Labels: enhancement

#380 https://github.com/uavorg/uavstack/issues/372
  com.creditease.uav.base/src/main/java/com/creditease/agent/workqueue/SystemTimerWorkMgr.java
Labels: bug

#384 GlobalFilterHandler supports jdk1.6 and above sorting capabilities.invokechain performance optimization.
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/jee/JEEServiceRunGlobalFilterHandler.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/appserver/listeners/GlobalFilterDispatchListener.java
Labels: enhancement

#386 correct cxf hook
  com.creditease.uav.hook.jaxws/src/main/java/com/creditease/uav/hook/jaxws/JaxWSCxfHookProxy.java
Labels: bug

#388 Base component SystemForkjoinWorker modification
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/logagent/TaildirLogComponent.java
  com.creditease.uav.base/src/main/java/com/creditease/agent/spi/IForkjoinWorker.java
  com.creditease.uav.base/src/main/java/com/creditease/agent/workqueue/SystemForkjoinWorker.java
  com.creditease.uav.collect/src/main/java/com/creditease/uav/collect/client/copylogagent/CopyOfProcessOfLogagent.java
Labels: enhancement
