Repository uavorg/uavstack, pull requests merged in 2018-09, with the labels that each got.

#390 Optimize the intercepting portion of the JDBC URL
  com.creditease.uav.monitorframework/src/main/java/com/creditease/uav/util/MonitorServerUtil.java
Labels: bug

#396 fix NPE problems caused by repeated registration of filters and servlets && adapt the context path configuration in springboot 2+
  com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/monitorframework/adaptors/SpringBootTomcatAdaptor.java
  com.creditease.uav.monitorframework/src/main/java/com/creditease/monitor/jee/servlet30/DynamicServletContextProcessor.java
  com.creditease.uav.tomcat.plus.core/src/main/java/com/creditease/tomcat/plus/interceptor/SpringBootTomcatPlusIT.java
Labels: bug, enhancement

#399 Monitor network card information
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/hbagent/handlers/HBClientDefaultHandler.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/uavnetwork/js/uav.network.js
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/NetworkHelper.java
  com.creditease.uav.helper/src/main/java/com/creditease/uav/helpers/network/HostNewworkInfo.java
Labels: enhancement

#398 Custom metrics display updates
  com.creditease.uav.agent/src/main/java/com/creditease/agent/feature/monitoragent/datacatch/BaseHttpMonitorDataCatchWorker.java
Labels: bug

#401 Increase the network card mac address
  com.creditease.uav.agent.heartbeat/src/main/java/com/creditease/agent/feature/hbagent/handlers/HBClientDefaultHandler.java
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/uavnetwork/js/uav.network.js
  com.creditease.uav.helper/src/main/java/com/creditease/agent/helpers/NetworkHelper.java
  com.creditease.uav.helper/src/main/java/com/creditease/uav/helpers/network/HostNewworkInfo.java
Labels: enhancement

#403 Fix invokechain NPE problem
  com.creditease.uav.monitorframework.apm/src/main/java/com/creditease/uav/apm/invokechain/handlers/ClientSpanInvokeChainHandler.java
Labels: bug

#405 fix issue 404
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/timesandtable/js/uav.tstable.js
Labels: bug

#408 In the charts component, the X axis data is not updated when the icon is redrawn.
  com.creditease.uav.console/src/main/webapp/apphub/js/common/charts.js
Labels: bug

#406 fix issue 404
  com.creditease.uav.console/src/main/webapp/uavapp_godeye/timesandtable/js/uav.tstable.js
Labels: bug
